# Generated by Django 4.1.5 on 2023-01-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=300)),
                ('year', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('birth', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
                ('person_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.people')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('votes', models.IntegerField()),
                ('movie_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
                ('person_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.people')),
            ],
        ),
    ]
