# Generated by Django 4.1.5 on 2023-01-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0002_remove_ratings_movie_id_remove_stars_movie_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.people')),
            ],
            options={
                'db_table': 'stars',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('votes', models.IntegerField()),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.movies')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.people')),
            ],
            options={
                'db_table': 'directors',
            },
        ),
    ]
