# Generated by Django 4.1.5 on 2023-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
        migrations.AlterModelTable(
            name='people',
            table=None,
        ),
    ]
