# Generated by Django 4.1.5 on 2023-01-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_movies_year_alter_people_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directors',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ratings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stars',
            table=None,
        ),
    ]
