# Generated by Django 4.1.5 on 2023-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_alter_directors_table_alter_ratings_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
